name: wavekeeper
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.17.5 
  scrollable_positioned_list: ^0.3.8
  spotify: ^0.13.6+1
  youtube_explode_dart: ^2.2.1
  audioplayers: ^6.0.0
  intl: ^0.19.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/album1.jpg
   - assets/album2.jpg
   - assets/album3.jpg
   - assets/album4.jpg
   - assets/album5.jpg
   - assets/album6.jpg
   - assets/album7.jpg
   - assets/album8.jpg
   - assets/album9.jpg
   - assets/album10.jpg
   - assets/album11.jpg
   - assets/album12.jpg
   - assets/logo.png
   - assets/top50.jpg
   - assets/wavekeeperlogo.jpg
   - assets/wavePB.jpg
   - assets/waveVar.jpg
   - assets/WaveKeeper.jpg
  